import Image from "next/image";
import { FaChevronCircleRight } from "react-icons/fa";

export default function Contact() {
  return (
    <div className="flex py-[100px] justify-center bg-[#3958e9]">
      <div className="main-container w-[100%]">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="fade-up p-[27px] text-white border-[2px] rounded-lg">
            <div className="md:text-xl">
              Read more in our AI Insider Newsletter
            </div>
            <div className="md:text-xl mt-2">
              Subscribe today to get the latest AI Insights
            </div>
            <div className="grid grid-cols-2 gap-2 mt-[46px] ">
              <div className="flex flex-col text-xs md:text-sm">
                <label htmlFor="fullname"> Full Name</label>
                <input
                  className="bg-white mt-2 focus:border-transparent text-black outline-none focus:ring-0 rounded-md px-[10] py-[7px] md:py-[10px] md:px-[14px]"
                  type="text"
                />
              </div>
              <div className="flex flex-col text-xs md:text-sm">
                <label htmlFor="fullname">
                  {" "}
                  <span className="hidden md:inline">WhatsApp or</span> Contact
                  Number
                </label>
                <input
                  className="bg-white mt-2 focus:border-transparent text-black outline-none focus:ring-0 rounded-md px-[10] py-[7px] md:py-[10px] md:px-[14px]"
                  type="text"
                />
              </div>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-[2fr_1fr] gap-2  mt-[46px] ">
              <div className="flex flex-col text-xs md:text-sm">
                <label htmlFor="fullname">Email Address</label>
                <input
                  className="bg-white mt-2 focus:border-transparent text-black outline-none focus:ring-0 rounded-md px-[10] py-[7px] md:py-[10px] md:px-[14px]"
                  type="text"
                />
              </div>
              <div className="flex flex-col justify-end text-xs md:text-sm">
                <button className="mt-2 text-white flex items-center justify-center gap-2  focus:border-white bg-[#18368f] border-[1px] outline-none focus:ring-0 rounded-md px-[10] py-[7px] md:py-[10px] md:px-[14px]">
                  <FaChevronCircleRight className="mb-1" /> Subscribe
                </button>
              </div>
            </div>
          </div>
          <div className="fade-up text-white min-h-[400px] flex flex-col justify-between rounded-lg">
            <div className="text-xl">
              {/* You have a new AI Insider Newsletter management @brandrev.ai */}
            </div>
            <div className="flex flex-col md:flex-row gap-5 md:gap-2 justify-between">
              <div className="flex gap-2">
                <Image
                  src="/logo/linkedin-putih.png"
                  alt="sample"
                  width={50}
                  height={50}
                  className="w-[50px] h-[50px] md:w-[80px] md:h-[80px]"
                />
                <div className="lg:max-w-[60%] leading-7 text-xs xl:text-[15px]">
                  Subscribe to our{" "}
                  <a className="underline">LinkedIn Newsletter</a> to get
                  instant updates every time we have a new post on LinkedIn.
                </div>
              </div>
              <div className="flex flex-col justify-end">
                <div className="text-[12px]">Generated by TuneAI</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
